<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl "href=".xsl" ?>
<!DOCTYPE product [
<!ELEMENT product (title, id, price, color, description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT description (#PCDATA)>
]>
<document>
<title>Inventory Management System</title>
   <product>
      <title>Soflyy T-Shirt (blue)</title>
      <id>999-B</id>
      <price>15</price>
      <color>blue</color>
      <description>Made of 100% cotton</description>
   </product>
   <product>
      <title>Soflyy T-Shirt (red)</title>
      <id>999-C</id>
      <price>15</price>
      <color>red</color>
      <description>Made of 100% cotton</description>
   </product>
   <product>
      <title>Soflyy Mug</title>
      <id>777-X</id>
      <price>150</price>
      <color>yellow</color>
      <description>This mug is awesome.</description>
   </product>
   <product>
      <title>Soflyy Mug</title>
      <id>777-O</id>
      
      <price>9</price>
      <color>orange</color>
      <description />
   </product>
   <product>
      <title>Soflyy Mug</title>
      <id>777-Y</id>
      <price>9</price>
      <color>yellow</color>
      <description />
   </product>
</document>